### ISSUE TITLE
Support API calls to alternate PyPi indexes

### ISSUE THREAD

**Issue by Stealthii** [owenlamont/uv-secure#41]
uv supports overriding the default index used for package resolution and operations, such as the following example (`~/.config/uv/uv.toml`):
```toml
[[index]]
name = "pypi"
url = "https://repo.example.com/artifactory/api/pypi/pypi-remote/simple"
default = true

[[index]]
name = "internal"
url = "https://repo.example.com/artifactory/api/pypi/pypi-local/simple"
```

It would be beneficial for uv-secure to support the use of whatever default index uv is configured to use, to reduce load on the Public API and to provide functionality to users in restricted countries or environments that cannot access the main PyPi registry.

---

One alternative is to provide an option to configure the PyPi endpoint URI (defaulting to `https://pypi.org/`), with relevant changes to config parsing, checking, and downloading to adhere to this option.

Alternatively, supporting any defined package registry (as noted in uv.lock) would negate the need for this option, provided errors are handled appropriately (in cases where the public API isn't proxied/mirrored fully, or registries don't publish compatible data for their internal packages).
