### ISSUE TITLE
Request: Add uvloop/winloop to an extra

### ISSUE THREAD

**Issue by Avasam** [owenlamont/uv-secure#45]
Instead of doing

```toml
[dependency-groups]
dev = [
  "uv-secure",
  "winloop; sys_platform == 'win32'",
  "uvloop; sys_platform != 'win32'",
]
```

I'd like to be able to do something like:
```toml
[dependency-groups]
dev = [
  "uv-secure[faster-async]",
]
```
